//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 02:04:10 AM IST 
//


package com.tscode.lawyersreckoner.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CaseHistory" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CaseNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="NumberOfDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PreviousDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PreviousStage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NextDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NextStage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "caseHistory"
})
@XmlRootElement(name = "CaseHistories")
public class CaseHistories extends DTO {

    @XmlElement(name = "CaseHistory", required = true)
    protected List<CaseHistory> caseHistory;

    /**
     * Gets the value of the caseHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the caseHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCaseHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseHistories.CaseHistory }
     * 
     * 
     */
    public List<CaseHistory> getCaseHistory() {
        if (caseHistory == null) {
            caseHistory = new ArrayList<CaseHistory>();
        }
        return this.caseHistory;
    }

	public void setCaseHistory(List<CaseHistory> ch) {
		// TODO Auto-generated method stub
		this.caseHistory=ch;
	}


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CaseNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="NumberOfDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PreviousDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PreviousStage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NextDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NextStage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   
}
