//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 02:06:05 AM IST 
//


package com.tscode.lawyersreckoner.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Client" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ClientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Adress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CaseNumbers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TotalFees" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FeesPaid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FeesPending" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "client"
})
@XmlRootElement(name = "Clients")
public class Clients extends DTO {

    @XmlElement(name = "Client", required = true)
    protected List<Client> client;

    /**
     * Gets the value of the client property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the client property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClient().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Clients.Client }
     * 
     * 
     */
    public List<Client> getClient() {
        if (client == null) {
            client = new ArrayList<Client>();
        }
        return this.client;
    }

	public void setClient(List<Client> client) {
		this.client=client;
		
	}


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ClientName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Adress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CaseNumbers" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TotalFees" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FeesPaid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FeesPending" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
   
}
